#!/usr/bin/ruby
# frozen_string_literal: true

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log($stdout)
end

def hide_log
  change_log(nil)
end
