# vim:foldmethod=marker

if [[ $ZPROF != "" ]]; then
  zmodload zsh/zprof
fi

# Make the $path array have unique values.
typeset -U PATH
function add_to_path_once() {
  path=("$1" $path)
}

export HISTFILE=~/.zsh_history
export HISTSIZE=20000
export SAVEHIST=20000

export CLICOLOR=1
export BLOCK_SIZE=human-readable # https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html

add_to_path_once "$HOME/.dotfiles/bin"
add_to_path_once "/usr/bin"
add_to_path_once "/opt/homebrew/bin"
add_to_path_once "/usr/local/bin"
add_to_path_once "/usr/sbin"
add_to_path_once "/sbin"
add_to_path_once "/usr/local/sbin"

export EDITOR='vim'
# export PAGER="col -b | vim -MR - "
# export MANPAGER='col -b | vim -MR -c ":set syntax=man" - '
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
export LANGUAGE=en_US.utf-8:C
export LC_TIME=en_DK.UTF-8
export LC_CTYPE=utf-8

# http://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Optimize-Options.html#Optimize-Options
export CFLAGS="-march=core2 -O3"

# Ruby performance tweaks, http://astrails.com/blog/2012/11/13/rvm-install-patched-ruby-for-faster-rails-startup
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_GC_HEAP_FREE_SLOTS=500000
export RUBY_GC_HEAP_INIT_SLOTS=1000000

# export JAVA_HOME=$(/usr/libexec/java_home)
# export DISABLE_AUTO_TITLE=true

setopt append_history
setopt auto_cd
setopt auto_pushd
setopt hist_expire_dups_first
setopt hist_fcntl_lock
setopt hist_ignore_all_dups
setopt hist_lex_words
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt interactivecomments
setopt no_case_glob
setopt prompt_subst # Make sure prompt is able to be generated properly.
setopt pushd_ignore_dups
setopt pushd_silent
setopt rm_star_wait
setopt share_history

unset GREP_OPTIONS

bindkey -e

if [[ ! -d "$HOME/.zgen" ]]; then
  git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
fi
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
  zgen load agkozak/agkozak-zsh-prompt
  zgen load zdharma/fast-syntax-highlighting
  zgen load zsh-users/zsh-completions
  zgen oh-my-zsh plugins/z
  zgen save
  echo "ZGen update, or it's plugins changed."
  echo "- Note that it does not remove the directory of unused/deprecated plugins"
  echo "- Have a look at the load time:"
  echo "    repeat 5 time zsh -ic exit; ZPROF=true zsh -ic exit"
fi

# zgen load agkozak/agkozak-zsh-prompt {{{
AGKOZAK_BLANK_LINES=1
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_PROMPT_CHAR=( ❯ ❯ ❮ )
AGKOZAK_CUSTOM_SYMBOLS=( 'Y' '!' '!' 'a' 'd' 'm' '>' ' ' )
# }}}

# zsh-users/zsh-syntax-highlighting {{{
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf*' 'fg=white,bold,bg=red')
# }}}

# zgen oh-my-zsh plugins/z {{{
unalias z
j() {
  if [[ -z "$*" ]]; then
    cd "$(_z -l 2>&1 | fzf-tmux +s --tac | sed 's/^[0-9,.]* *//')"
  else
    _last_z_args="$@"
    _z "$@"
  fi
}
# }}}

# brew install fzf && brew install the_silver_searcher {{{
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export FZF_COMPLETION_TRIGGER=''
export FZF_COMPLETION_OPTS=
source ~/.fzf.zsh
# Use ag instead of the default find command for listing candidates.
# - The first argument to the function is the base path to start traversal
# - Note that ag only lists files not directories
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  # brew install the_silver_searcher
  ag -g "" "$1"
}
bindkey '^P' fzf-history-widget
bindkey '^N' fzf-history-widget
# }}}

add_to_path_once "./bin"
add_to_path_once "~/.cargo/bin"

# Enable completions
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:(cp|mv):*' file-sort modification

source $HOME/.dotfiles/zsh/aliases
source $HOME/.dotfiles/zsh/functions
[[ -f $HOME/.zshrc_private ]] && source $HOME/.zshrc_private

# Unset local functions
unset -f add_to_path_once

source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

if [[ $ZPROF != "" ]]; then
 zprof | less
fi
