alias aliases="cd ~/.dotfiles && \$EDITOR ${0:a} && source ${0:a}; popd"
alias zshrc='cd ~/.dotfiles && $EDITOR lib/zshrc && source lib/zshrc; popd'
alias vimrc='cd ~/.dotfiles && $EDITOR lib/vimrc; popd'
alias tmuxrc='cd ~/.dotfiles && $EDITOR lib/tmux.conf && tmux source-file lib/tmux.conf; popd'
alias gitrc='cd ~/.dotfiles && $EDITOR --cmd "set filetype=gitconfig" lib/gitconfig; popd'
alias gems='$EDITOR ~/.rbenv/default-gems'
alias migrate='bundle exec rake db:migrate db:test:clone parallel:prepare'
alias rollback='bundle exec rake db:rollback'
alias myip='ifconfig en0 | grep  inet\  | cut -d \  -f2'
alias du='dust'
alias ls='eza --icons=auto'
alias t='task'
alias g='git'
