#!/usr/bin/ruby
# frozen_string_literal: true

puts "Loading config from : #{__FILE__}"

require 'irb/completion'

IRB.conf[:AUTO_INDENT] = true
IRB.conf[:HISTORY_FILE] ||= File.join(ENV['XDG_DATA_HOME'], 'irb', 'history')
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:SAVE_HISTORY] = 1000
# IRB.conf[:USE_READLINE] = true
